### ISSUE TITLE
Missing/wrong new line character?

### ISSUE THREAD

**Issue by Inversion-NL** [mickem/medin.name.temperature#1]
There is something funny with the new line character.

Both Github as well as Atom editor doesn't understand your new lines.

![image](https://user-images.githubusercontent.com/15921016/70608904-394b4280-1c01-11ea-863d-fc68df27ec67.png)

![image](https://user-images.githubusercontent.com/15921016/70608931-42d4aa80-1c01-11ea-842d-6a270b679a7b.png)

**Comment by mickem** [comment]
The code is written in typescript and compiled so that is the "compiled" version.
Look for project folder for sources.
