### ISSUE TITLE
[Translation] Translations

### ISSUE THREAD

**Issue by Inversion-NL** [mickem/medin.name.temperature#4]
When your ready for it: 
I'd like to translate your app to Dutch.

**Comment by mickem** [comment]
That would be awesome!

I have, currently, intentionally not translated anything as I need to look at homey composer (managing the app.json by hand is error prone) and how to integrate it with some localization package first.
So perhaps in a week or two I will be ready for translations.

**Comment by Inversion-NL** [comment]
No problem, I understand.

**Comment by mickem** [comment]
Translations can now be done here: https://poeditor.com/join/project/frV5jaW4lg please do let me know if there are any issues and feel free to review current translations as they are machine translated

**Comment by Inversion-NL** [comment]
Dutch is done 😎

**Comment by mickem** [comment]
How was the quality of the machine translations?
I.e. will it make sense to use machine translation for other languages?

**Comment by Inversion-NL** [comment]
Quite good actually!
There are some translations which are hard for the machine to understand of course. 
Because not understanding the context of the words.

**Comment by mickem** [comment]
Great will translate the others as well then... thanks!
