### ISSUE TITLE
[Feature request] Set a zone monitoring by flow

### ISSUE THREAD

**Issue by Inversion-NL** [mickem/medin.name.temperature#5]
I'd like to have the ability to set the monitoring level by flow.

Example:
**when**
termostat set temperature changes 
**and**
set temperature > 18c
**then**
 set 'monitoring level' to 'monitoring enabled'

**Comment by mickem** [comment]
Sounds like a very good idea.

**Comment by mickem** [comment]
Added to latest test version, not sure how one can access those now with the new app store...

**Comment by mickem** [comment]
Apparently you can get it here: https://homey.app/sv-se/app/name.medin.temperatures/Temperature-manager/test/

Full disclosure, I havent tested this extensively, so your mileage may vary...

**Comment by Inversion-NL** [comment]
Great!
I'll test and let you know.

**Comment by Inversion-NL** [comment]
Yes, there is a test version available.
